---

- name: Setup packages on servers
  hosts: all
  roles:
    - common
- name: Setup nginx on LB
  hosts: loadbalancer
  roles:
    - geerlingguy.nginx

- name: Start GO APP
  hosts: application
  roles:
    - hathbanger.startApp
