FROM ubuntu:16.04
RUN apt-get update && \
	apt-get install locales && \
	apt-get install -y \
		iputils-ping \
		openssh-server \
		sudo \
		python \
		python-apt

RUN locale-gen en_US.UTF-8
RUN mkdir /var/run/sshd
COPY id_rsa.pub /root/.ssh/authorized_keys

EXPOSE 22 80

CMD ["/usr/sbin/sshd", "-D", "-4"]